#cloud-config
write_files:
  - path: /root/remove-ssh.sh
    permissions: '0755'
    owner: root:root
    content: |
      #!/bin/bash
      set -e
      apt-get purge -y openssh-server
      for svc in ssh sshd; do
        if systemctl is-active --quiet $svc; then
          systemctl stop $svc 2>/dev/null
        fi
        if systemctl list-unit-files | grep -q "^${svc}.service"; then
          systemctl disable $svc 2>/dev/null
        fi
      done
      rm -rf /etc/ssh /var/run/sshd /root/.ssh /home/azureuser/.ssh
      pkill -f sshd

  - path: /root/startup.sh
    permissions: '0755'
    owner: root:root
    content: |
      #!/bin/bash
      set -e  
      cd /root
      git clone https://github.com/comrade-coop/aapp-toolkit.git
      cd aapp-toolkit
      bash bootstrap/init.sh

runcmd:
  - chmod +x /root/remove-ssh.sh
  - /root/remove-ssh.sh
  - chmod +x /root/startup.sh
  - /root/startup.sh