#cloud-config
package_update: true
package_upgrade: true

# Remove unwanted packages
packages:
  - git  # Ensure git is installed

packages_remove:
  - openssh-server

# Create the startup script
write_files:
  - path: /root/startup.sh
    permissions: '0755'
    owner: root:root
    content: |
      #!/bin/bash
      set -e  
      cd /root
      git clone https://github.com/comrade-coop/aapp-toolkit.git
      cd aapp-toolkit
      bash bootstrap/init.sh

# Execute startup script after cloud-init completes
runcmd:
  - chmod +x /root/startup.sh
  - /root/startup.sh
